Switch to crossterm backend, async input
carzum/termviz pull request #72
Opened 2023-01-17 21:50 UTC by carzum

Fixes #71

2023-01-20 13:37 UTC, Eman7C7 requested changes
All good except the backspace thing

2023-01-20 13:37 UTC, Eman7C7 commented on src/main.rs
> +            "Enter" => (KeyCode::Backspace, v.clone()),
Backspace as Enter?

2023-01-21 09:39 UTC, Eman7C7 approved these changes

2023-01-22 16:00 UTC, MaxiMaerz approved these changes

2023-01-22 16:00 UTC, MaxiMaerz commented on src/main.rs
> +    // restore terminal
nice

2023-01-22 16:16 UTC, carzum commented on src/main.rs
> +#[tokio::main]
the macro allows the function to be async. https://tokio.rs/tokio/tutorial/hello-tokio

2023-01-22 16:24 UTC, merged